# Docker Compose (v2)

version: "2"
services:

  web_scripts:
    build:
      context: docker/images/ci
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    environment:
      - DRUPAL_SETTINGS=production
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
    volumes:
      - ./:/var/www
    container_name: siteopendata_web_scripts

  web:
    build:
      context: docker/images/ci
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    environment:
      - DRUPAL_SETTINGS=production
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    ports:
      - "9000"
    container_name: siteopendata_web

  postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=od
      - POSTGRES_USER=od
      - POSTGRES_PASSWORD=od
    volumes:
      - db_data:/var/lib/postgresql
      - ./files_private/od:/database/
    ports:
      - "5432:5432"
    container_name: siteopendata_postgres

  nginx:
    image: nginx:alpine
    volumes:
     - ./html:/var/www/html
     - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - web
    restart: always
    container_name: siteopendata_nginx

  hub:
    image: drupalcomposer/selenium:hub
    ports:
      - "4444:4444"
    depends_on:
     - postgres
     - web
    container_name: siteopendata_hub

  firefox:
    image: drupalcomposer/selenium:node-firefox
    depends_on:
     - postgres
     - web
     - hub
    container_name: siteopendata_firefox

volumes:
  db_data:
