# Docker Compose (v2)

version: "2"
services:

  web:
    build:
      context: docker/images/dev
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    environment:
      - DRUPAL_SETTINGS=development
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
    volumes:
      - ./:/var/www
    depends_on:
      - db
    ports:
      - "9000"
    container_name: siteopendata_web

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wxt
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    container_name: siteopendata_db
    command: mysqld --max_allowed_packet=32M

  postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=od
      - POSTGRES_USER=od
      - POSTGRES_PASSWORD=od
    volumes:
      - db_data:/var/lib/postgresql
      - ./files_private/od:/database/
    ports:
      - "5432:5432"
    container_name: siteopendata_postgres

  nginx:
    image: nginx:alpine
    volumes:
     - ./html:/var/www/html
     - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - web
    restart: always
    container_name: siteopendata_nginx

  cron:
    build:
      context: docker/images/cron
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    environment:
      - DRUPAL_SETTINGS=development
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
    volumes:
      - ./:/var/www
    depends_on:
     - db
     - web
    container_name: siteopendata_cron

  hub:
    image: drupalcomposer/selenium:hub
    ports:
      - "4444:4444"
    depends_on:
     - db
     - web
    container_name: siteopendata_hub

  firefox:
    image: drupalcomposer/selenium:node-firefox
    depends_on:
     - db
     - web
     - hub
    container_name: siteopendata_firefox

  mailhog:
    image: mailhog/mailhog
    hostname: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    container_name: siteopendata_mailhog

  solr:
    image: solr:6-alpine
    hostname: solr
    ports:
      - "8983:8983"
    volumes:
      - ./docker/conf/solr/drupal:/opt/solr/server/solr/configsets/drupal/conf
      - ./files_private/mycores:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-create
      - -c
      - drupal
      - -d
      - /opt/solr/server/solr/configsets/drupal
    container_name: siteopendata_solr

volumes:
  db_data:
    driver: local
